# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# override variables
variables:
  trmnl: {
    plugin_settings: {
      instance_name: 'Nashville Electric Service (NES)'
    },
    user: {
      time_zone: Central Time (US & Canada),
      time_zone_iana: America/Chicago,
      utc_offset: -18000,
      locale: 'en-US'
    }
  }