---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://www.nespower.com/outagemap/getall
polling_headers: accept=application/json
polling_body: 
id: 112378
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  description: Show the number of customers without power in Nashville, Tennessee
  github_url: https://github.com/stephenyeargin/trmnl-nashville-electric-service
  learn_more_url: https://www.nespower.com
  email_address: stephen@yearg.in
- keyname: thunderforest_api_key
  field_type: password
  name: Thunderforest API Key
  description: Use for <a href="https://www.thunderforest.com/maps/mobile-atlas/" class="underline">nicer looking maps</a>
  placeholder: ABCDefg1234
  required: false
name: Nashville Electric Service (NES)
refresh_interval: 15
